### PR TITLE
New version v3.0.0 - Make it more easy and simple to use

### PR DESCRIPTION
**Pull request by BenjaminFourmaux**
Hello Grafana team !

When I looking for a plugin to display the state of a healthcheck, on my dashboard, I came across this plugin but I fond it complicated to use and to match whith my simple need. I decided to fork it and make it simpler.

Now, users can define their own thresholds (background color, severity name and value). Threshold activate when the query value is in range. Only works with number values.
Alert was removed.
Remake the multipane view
This version are **breaking changes**. Older versions are not supported.

### CODE REVIEW

**Comment by SckyzO** [comment]
Hello, 
This version doesn't support multi metrics in the same panel, right ? 
I use Status Panel to show many metrics, each panel have 10/15 metrics. But with you version, i can only use one metric. 
And I can't use thresholds color in override option, So this feature would be very interresting :) 

Thanks

**Comment by BenjaminFourmaux** [comment]
> Hello, This version doesn't support multi metrics in the same panel, right ? I use Status Panel to show many metrics, each panel have 10/15 metrics. But with you version, i can only use one metric. And I can't use thresholds color in override option, So this feature would be very interresting :)
> 
> Thanks

Hi, thank you for your feedback !
I thought that not many people use multi metrics in one panel feature. I will try to implement it.

**Comment by ToropovAV** [comment]
> > Hello, This version doesn't support multi metrics in the same panel, right ? I use Status Panel to show many metrics, each panel have 10/15 metrics. But with you version, i can only use one metric. And I can't use thresholds color in override option, So this feature would be very interresting :)
> > Thanks
> 
> Hi, thank you for your feedback ! I thought that not many people use multi metrics in one panel feature. I will try to implement it.

Hi, I would call support for multiple metrics the main feature of this plugin. There is a similar plugin where this is implemented, but it was also abandoned https://github.com/serrrios/Status-Overview-Panel

**Comment by SckyzO** [comment]
Yes, I use this main feature with this plugin, but this PR#6 (versionned 3.0) doesn't support it. 

Check this : 
image

And each panel is configured to show ~15 metrics by panel. It is mandatory to have this main feature to me.

**Comment by BenjaminFourmaux** [comment]
**Now support Multi pane !**

I adding the support of multi pane in one panel. Just add more queries.
I adding template string to add variable in text fields (title, subtitle and url)

I wanted to make each pane customizable but that would have made the plugin complicated and cumbersome to use. Which is contrary to v3
image

**Comment by SckyzO** [comment]
> **Now support Multi pane !**
> 
> I adding the support of multi pane in one panel. Just add more queries. I adding template string to add variable in text fields (title, subtitle and url)
> 
> I wanted to make each pane customizable but that would have made the plugin complicated and cumbersome to use. Which is contrary to v3 image

Hmmm. And, if you add a global plugin option like

- Button -> concatenate all metrics in a panel (yes/no).

And then we can override the options by fields

- Status panel - thresholds

Is it possible to add an option to show or hide the value/label if it is not in OK state?

My need is to have, in one panel, many metrics, to monitor many computes/nodes/storages. And if one of these metrics exceeds the threshold, my panel changes color and according to the thresholds configuration.

**Comment by SckyzO** [comment]
I can create a request on your github :)

**Comment by tolzhabayev** [comment]
@BenjaminFourmaux we are currently not looking to introduce breaking changes as we are mostly trying to offer a react version of this plugin working for existing customers. You are however free to fork and publish an alternative version of this panel and [submit it for review](https://grafana.com/developers/plugin-tools/publish-a-plugin/publishing-best-practices)

**Comment by BenjaminFourmaux** [comment]
Hey @tolzhabayev thank you for you reply.
I think i have a stable version, prod-ready of my version, i will definitely propose to submit an alternative version of this plugin.

**Pull request closed without merging**
